---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/nutrimo_test
    username: sinorang
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update     # 개발 편의, 운영에서는 금지.
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

  sql:
    init:
      mode: never