spring:
  application:
    name: nutrimo_admin
  profiles:
    active: local   # 기본 프로파일

  jackson:
    time-zone: Asia/Seoul        # API 응답 직렬화 시간대
    date-format: yyyy-MM-dd'T'HH:mm:ss

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090
  servlet:
    context-path: /admin

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

# JWT 관련 (공통)
#jwt:
#  secret: ${JWT_SECRET:change-me-in-prod}  # 환경변수로 주입
#  expiration:
#    access-token: 3600000     # 1시간(ms)
#    refresh-token: 1209600000 # 14일(ms)